version: "3.8"

services:
    php:
        build:
          dockerfile: ./.infrastructure/docker/php/Dockerfile
          context: .
        volumes:
            - .:/var/www/html:cached
        env_file: .env

    nginx:
        build:
          dockerfile: ./.infrastructure/docker/nginx/Dockerfile
          args:
            - PHP_FPM_ENV=docker
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html:cached
        depends_on:
            - php
            - postgresql

    postgresql:
        image: postgres:15-alpine3.17
        volumes:
            - postgresql_volume:/var/lib/postgresql/data
        env_file: .env
        ports:
          - 5432:5432

    adminer:
      image: adminer:latest
      ports:
       - "8082:8080"
      depends_on:
        - postgresql

volumes:
    postgresql_volume:
